### ISSUE TITLE
No positive samples when selecting disease types

### ISSUE THREAD

**Issue by jaclyn-taroni** [cognoma/core-service#100]
There appears to be an issue with the positive samples (perhaps in the mutations table?). If I add _KRAS_ to my query, none of the 33 disease types have any positive samples. I also tried this with _TP53_ and encountered the same problem.

**Comment by cgreene** [comment]
I think I just saw something go by from @kurtwheeler mentioning that this is known and fixable. However, I can't find it right now.

**Comment by kurtwheeler** [comment]
That's correct. I have a PR/deployment I need to do fire off.

**Comment by kurtwheeler** [comment]
@jaclyn-taroni, it appears this is resolved:

![image](https://user-images.githubusercontent.com/4026833/40506137-8757af8c-5f64-11e8-8e60-66f3de343cc6.png)
