### ISSUE TITLE
Specify python version

### ISSUE THREAD

**Issue by dhimmel** [cognoma/core-service#14]
Currently we have a [`requirements.txt`](https://github.com/cognoma/django-cognoma/blob/7f0a34b5b53031e728ec5c28a27e378f4f217ca0/requirements.txt), but we don't specify our Python version.

I support using Python 3.5, so we can take advantage of the improved language. Package support shouldn't be an issue, since [most packages now are Python 3 compatible](http://py3readiness.org/). And if a package does not yet support Python 3, I don't think it's good technology to learn for the future.

**Comment by dcgoss** [comment]
+1 for Python 3. Future!

**Comment by dhimmel** [comment]
@awm33 I remember the backend group made a decision over which python a few weeks back. Do you remember what that was?

**Comment by dhimmel** [comment]
Ah it looks like Python 3.5 was the decision according to https://github.com/cognoma/django-cognoma/issues/22.

**Comment by awm33** [comment]
@dhimmel I think python 3 was decided. Unless there are issues with any of the django/rest packages, 3.5.x seems fine.
