### ISSUE TITLE
[HackNight] 08/09/16 Meeting minute

### ISSUE THREAD

**Issue by maxdml** [cognoma/core-service#17]
_Note: This is an intent to formalize hacknights outcomes and todo list_
_Note2: I assume this project is the (maybe temporary) placeholder for backend development_

HackNight reference: http://www.meetup.com/DataPhilly/events/233070705/

The following points were mentioned. Some related issues are already existing, while others aren't.
**All attendants are warmly encouraged to discuss this summary**

- New architecture proposal (please update the picture)
- **Need for specification**: Front-end API (interface between the JavaScript UI and the "backend") [Link to issue](https://github.com/cognoma/django-cognoma/issues/16).
- **Need for specification**: Asynchronous Task Queue (ATQ) (interface between the django backend and the ML module(s))
- **Need for specification**: Machine Learning API (interface between the ATQ and the Machine Learning module(s))
- **Need for specification**: Containers deployment (to start with, a basic microservice breakdown through docker). We need to draw the rough lines of which software module goes where (i.e is an independently deploy-able unit, with its own - and specifed - APIs)
- **Need for diagram**: Database layout. The purpose of this diagram is only to map data to modules. At this time we can cope with imprecision about the scale of data.
- **Need for directive**: How to contribute to django-cognoma. [Link to issue](https://github.com/cognoma/django-cognoma/issues/8)

Next meeting: in 2 weeks [_please confirm / update with exact date, time and location_]

**Comment by maxdml** [comment]
As an exemple of strong API documentation, I believe [OpenStack](http://docs.openstack.org/api/api-specs.html) is a good start. Note how every module's API is listed, and how for each of those modules each route is described.

**Comment by cgreene** [comment]
Thanks @maxdml! I would add as an item that this team needs to come up with contributor guidelines (#8). Right now, it's unclear how one contributes code, ideas, etc to the django part of the cognoma team.

**Comment by cgreene** [comment]
#8 now closed thanks to PR #18

**Comment by awm33** [comment]
I think everything in here has been addressed. If there is an individual item that you do not think had been addressed, please open an issue for it.
