### ISSUE TITLE
Docker Environments

### ISSUE THREAD

**Issue by awm33** [cognoma/core-service#21]
- Testing Environment
- Production Environment
- Development Environment?

django-cognoma and task-service both use python+postgres

See implementation diagram https://github.com/cognoma/cognoma#implementation-details

**Comment by dcgoss** [comment]
I am going to make a Dockerfile and create a screencast showing the best development workflow, going from writing code to committing with Git to testing with Docker.

**Comment by awm33** [comment]
We now have docker setup for development and local testing using docker-compose, production using AWS Elastic Container Service, and CircleCI builds it's own container based on circle.yml.
