### ISSUE TITLE
Gene Search

### ISSUE THREAD

**Issue by awm33** [cognoma/core-service#29]
The Cognoma team would like to provide some search functionality to assist the user during gene selection.

Options include:
- Simple LIKE operation on the field(s) to be searched
- Postgres full text search
- Elasticsearch

The Greene Lab has already used elasticsearch with the django-genes model that we're including in this project. They [used haystack](https://bitbucket.org/greenelab/django-genes/src/97e726e4ffb32face078246516c4d30f679ab04a/genes/search_indexes.py) which is a django elasticsearch library.

There is a [haystack library for django rest framework](https://github.com/inonit/drf-haystack).

If the search is simple, or doesn't need full text capabilities, then LIKE is the simplest solution.

Postgres full text search would mean one less moving part. Here is a [good blog post on setting it up in the django rest framework](http://www.machinalis.com/blog/full-text-search-on-django-rest-framework/)

Elasticsearch has already been used with this model and provides advanced search capabilities, but would mean running another server. AWS does have a hosted elasticsearch solution, and setup can be pretty simple. I've also used elasticsearch for a lot of things, including searching medical records.

I think we should start by getting some examples.

@cgreene @dhimmel @gwaygenomics Can you provide some examples queries? Literally what a user would be typing, along with how you think it would connect to the gene model, like "this person is typing in part of a standard name" or something similar. CC'ing @BobMiller @bdolly

**Comment by dhimmel** [comment]
Here's the head of our [genes dataset](https://github.com/cognoma/genes/blob/721204091a96e55de6dcad165d6d8265e67e2a48/data/genes.tsv):

| entrez_gene_id | symbol | description | chromosome | gene_type | synonyms | aliases |
|----------------|----------|------------------------------------|------------|----------------|------------------------------|-------------------------------------------------------|
| 1 | A1BG | alpha-1-B glycoprotein | 19 | protein-coding | A1B\|ABG\|GAB\|HYST2477 | alpha-1B-glycoprotein\|HEL-S-163pA\|epididymis secretory sperm binding protein Li 163pA |
| 2 | A2M | alpha-2-macroglobulin | 12 | protein-coding | A2MD\|CPAMD5\|FWP007\|S863-7 | alpha-2-macroglobulin\|C3 and PZP-like alpha-2-macroglobulin domain-containing protein 5\|alpha-2-M |
| 3 | A2MP1 | alpha-2-macroglobulin pseudogene 1 | 12 | pseudo | A2MP | pregnancy-zone protein pseudogene |

Each gene has a primary symbol (`symbol`), primary description (`description`), alternative symbols (`synonyms`, pipe delimited), and alternative descriptions (`aliases`, pipe delimited).

When someone searches for a gene, the search terms should be matched against all four fields (`symbol`, `description`, `synonyms`, `aliases`). Regarding the ranking of hits, preference should be given for matches to primary fields and complete matches. By complete match, I mean a search for `ABC` should rank a gene with symbol `ABC` over a gene with symbol `ABCD`.

**Comment by dhimmel** [comment]
BTW, in the above post, I'm not sure exactly which django-genes columns correspond to `symbol`, `description`, `synonyms`, and `aliases`. I [opened an issue](https://bitbucket.org/greenelab/django-genes/issues/5/confusion-over-standard_name-and) which should give me a better understanding.

**Comment by cgreene** [comment]
We have had good luck with elastic because of the difficulties of determining what a user is searching. I think that django-genes boosts some of the fields and weighs genes based on their annotations to attempt to - most frequently - return the gene that the user is (we hope) looking for.

Something that just occurred to me - we might be able to outsource search to mygene.info from @andrewsu and @newgene - which also provides an existing API if we don't want to host elastic search ourselves. We haven't yet tried it for our projects, but it could be ideal for this.

**Comment by dhimmel** [comment]
Just tried out mygene.info and it's slick. Here's an example query:

```
https://mygene.info/v3/query?q=ihh&species=human&entrezonly=true
```

which returns

```json
{
  "total": 3,
  "max_score": 433.97708,
  "took": 3,
  "hits": [
    {
      "_id": "3549",
      "_score": 433.97708,
      "entrezgene": 3549,
      "name": "indian hedgehog",
      "symbol": "IHH",
      "taxid": 9606
    },
    {
      "_id": "26012",
      "_score": 0.45286167,
      "entrezgene": 26012,
      "name": "NMDA receptor synaptonuclear signaling and neuronal migration factor",
      "symbol": "NSMF",
      "taxid": 9606
    },
    {
      "_id": "64399",
      "_score": 0.4227362,
      "entrezgene": 64399,
      "name": "hedgehog interacting protein",
      "symbol": "HHIP",
      "taxid": 9606
    }
  ]
}
```
This payload has everything we need for gene display. There may be some issues with our version of Entrez Gene being different from their version of Entrez Gene. Errors will be infrequent, but we should check that a gene selected by mygene.info exists in our dataset before allowing the user to add it. You could always just subset `hits` for `entrezgene` IDs that are in our dataset.

**Comment by awm33** [comment]
@cgreene @dhimmel Elasticsearch hosting my not be difficult, but I thought it was worth noting. Elasticsearch hosting really only gets complicated with multiple sharded nodes and backup on those multiple nodes. The genes table is tiny, so that won't be an issue here. Another benefit to using elasticsearch would be that we could also index the classifier and other objects for search if we want.

@dhimmel 

> but we should check that a gene selected by mygene.info exists in our dataset before allowing the user to add it.

That would add some lag, since two sequential HTTP requests would have to happen per key press.

> You could always just subset hits for entrezgene IDs that are in our dataset.

Wouldn't that mean keeping the list of the 20k entrez IDs in client memory?

@dhimmel @cgreene Both mygene.info and elasticsearch seem viable, but have their own pros/cons. Let me know what you guys think

**Comment by cgreene** [comment]
Hosted elastic (setup on node or via elastic-as-a-service) is pretty easy and would match our server.

On the other hand, 20k ints in memory shouldn't be horrible - and I'd suspect that we could come up with a quick way to check that via whatever javascript's equivalent of a hash map style data type is.

I do not have strong feelings either way. I love having less to maintain, but would understand if we don't feel that mygenes.info quite fits the use case yet.

**Comment by awm33** [comment]
@cgreene Yeah, not something really pointing either way from a software standpoint. We may have to deal with CORS headers, but that's just an nginx config issue and we probably have to deal with it to access the neo4j server anyway.

Something that might push it is if we want to offer search capabilities for other objects, like classifier.

Another option may be something like [http://elasticlunr.com/](http://elasticlunr.com/) in a web worker.

**Comment by cgreene** [comment]
Whoa - hadn't seen elasticlunr. That's pretty nifty.

**Comment by cgreene** [comment]
If we definitely want autocomplete, it's implemented as a wildcard-type approach on http://mygene.info
https://github.com/SuLab/mygene.info/issues/4#issuecomment-252731552

I don't think that we plan to offer search for specific samples (though we do plan to have faceting/filtering by disease type and maybe other criteria) so we probably won't use it there. I don't know that we currently plan to offer search capabilities for classifier, but I agree that if we do an in-cognoma elasticsearch and/or elasticlunr makes the most sense. At that point we might as well use it for genes as well.

**Comment by gwaygenomics** [comment]
> I don't think that we plan to offer search for specific samples (though we do plan to have faceting/filtering by disease type and maybe other criteria) so we probably won't use it there.

This is probably not MVP - but I could see a use case where a researcher may want to hone in a specific sample. We could probably not to painfully point them to a cBioportal sample like [this](http://www.cbioportal.org/case.do?cancer_study_id=brca_tcga&sample_id=TCGA-AC-A3YJ-01)

**Comment by dhimmel** [comment]
Regarding autocomplete, I don't think we want to allow users to select genes based only on their symbol. Users should have to click on the card that includes the symbol plus name to avoid errors. I do think that as a user types, the displayed cards should get filtered for genes with partial or complete matches. I believe this is how the [current wireframe](https://github.com/cognoma/uiux/blob/29f0638cac927b6347d2d7e62b08ca477e9e1a10/wireframes/exports/invision_app_prototype/1.1-Cognoma-GeneSelection-SEARCH.jpg) is designed.

**Comment by awm33** [comment]
@dhimmel @cgreene Have we decided to go with mygene.info? If so, I think we should close this issue.

**Comment by bdolly** [comment]
@awm33 @dhimmel @cgreene I quick and dirty gene search working in my local build using mygene.info and it seems to work pretty fast and well. Hopefully this week I'll be able to write a mock backend for it and some tests and make a PR. 

I need to know what params we would be passing with the query based on http://mygene.info/v3/api/#MyGene.info-gene-query-service-GET-Gene-query-service

**Comment by cgreene** [comment]
I agree with mygenes.info

**Comment by dhimmel** [comment]
# Preliminary mygene.info query for partial symbol search

> I need to know what params we would be passing with the query

@bdolly for now let's go with the following query:

https://mygene.info/v3/query?q=SEARCH_GOES_HERE*&suggest_from=symbol^2,alias&species=human&entrezonly=true

So for example, if a user typed `GABA`, we would perform the following query: https://mygene.info/v3/query?q=GABA*&suggest_from=symbol^2,alias&species=human&entrezonly=true. This query supports partial matching (the `*` allows matching any symbol that starts with `GABA`). This query will not match by full names, just by gene symbols. However, once https://github.com/SuLab/mygene.info/issues/4 is implemented, we will update this query to also match by gene name.
