### ISSUE TITLE
Status/'y' selector

### ISSUE THREAD

**Issue by cgreene** [cognoma/core-service#3]
This is a very brief description that we'll need to flesh out more, particularly with help from @gwaygenomics:

Cognoma will provide the opportunity to construct a supervised machine learning model that predicts a feature of interest. For example, mutations of genes in a specific pathway.

We anticipate that this endpoint will allow the user to specify a set of genes and samples. The endpoint would return the number of samples that contain alterations within that set.

**Comment by gwaygenomics** [comment]
I think this step is where the user will start. They will have the option to input their own list of genes or the option to be assisted by @dhimmel's [hetnets](https://neo4j.het.io/browser/). There should also be options to filter [mutation types ](https://ghr.nlm.nih.gov/primer/mutationsanddisorders/possiblemutations) depending on expected pathogenicity. 

This step should inform the tissue/sample selector and give suggestions based on tissues relevant to the query.

**Comment by awm33** [comment]
https://github.com/cognoma/core-service/pull/25
