### ISSUE TITLE
Task creation and expansion

### ISSUE THREAD

**Issue by awm33** [cognoma/core-service#30]
When a classifier is created, we need to queue a task in the task server. When classifier objects are retrieved or listed using the REST API, the task should be available for expansion as a child.

Looking at using this [RemoteField](https://github.com/rockabox/django-remote-field) library, or potentially rolling my own since this doesn't like compabilable with [djangorestframework-expander](https://github.com/silverlogic/djangorestframework-expander), which works well. Might be a good opportunity for a mini open source lib of my own. Would really help for using django rest framework for microservices.

@dbolly @BobMiller Is the frontend going to keep the classifier in-memory before it's ready to go, or persist it before then? If it needs to be persisted before then, we need to track the frontend state with a new field. Basically, if it's ready to be queued, but you may want to track more states for the wizard like UI, so the user can pick up where they left off.

**Comment by dcgoss** [comment]
Resolved by https://github.com/cognoma/core-service/pull/74
