### ISSUE TITLE
Add filter to and field selection to /samples

### ISSUE THREAD

**Issue by awm33** [cognoma/core-service#33]
In response to the needs presented in https://github.com/cognoma/cancer-data/pull/29 we need to add the ability for the frontend to get a list of samples related to a given mutated gene.

Example:
`/samples?mutations__gene=1234&mutations__status=true&&fields=sample_id`

Looks like the [SearchFilter class](http://www.django-rest-framework.org/api-guide/filtering/#searchfilter) supports filtering related models. The [dynamic fields](https://github.com/dbrgn/drf-dynamic-fields) library can be used to filter fields. Note: Even though the examples use ModelSerializer, it should work with the regular Serializer used in this repo.

**Comment by dhimmel** [comment]
Would it be possible to specify a list of genes as well and for each gene receive a list of samples with that mutation?

**Comment by awm33** [comment]
@dhimmel The endpoint returns sample objects with mutations being a child. I think what you're describing might be achieved through `/samples?mutations__gene=1234&mutations__gene=2356&mutations__gene=21883&fields=sample_id,mutations`

Maybe adding mutations as a searchable relation on /genes may make sense as well. For example `/genes? entrezid=90808&entrezid=89979&entrezid=8668&mutations__status=true&expand=mutation&fields=entrezid`

Then gene.mutations[...].sample would have the sample ids.

I just used 3 as an example, idk how many genes would be typical.
