### ISSUE TITLE
Need to use an application server like uwsgi

### ISSUE THREAD

**Issue by Ahmed** [cognoma/core-service#39]
Hi team,

One thing I noticed is the backend is using the built in development server that comes with Django.
It's not suitable for production environment,  you can get a better performance by using app server like uwsgi.

Another thing, nginx might not be needed if you use uwsgi directly without using static files like images and css in the backend. It looks like this app is used only as an api end point.  

If you need to modify any headers in the returned request, you can have that in a middle ware, and have all the requests have any headers you want.

--
Ahmed

**Comment by awm33** [comment]
@Ahmed Would you be interested in taking this on? Perhaps creating a prod Dockerfile in config/prod?

I found this [example repo](https://github.com/dockerfiles/django-uwsgi-nginx) for using uwsgi in Docker. It uses supervisord to run the uwsgi process. It also places nginx in front of it, though idk if that's necessary, maybe uwsgi+supervisord is all that's needed.

We may still need nginx in front of the services to route certain paths to certain services. We may be able to use the new AWS applications load balancer to achieve the routing instead.

**Comment by awm33** [comment]
Resolved by https://github.com/cognoma/core-service/pull/48
