### ISSUE TITLE
Algorithms Model/Endpoint

### ISSUE THREAD

**Issue by cgreene** [cognoma/core-service#4]
Cognoma will need to be able to return a list of the supported algorithms, as well as the characteristics of those algorithms relevant for the algorithm selector.

**Comment by gwaygenomics** [comment]
Once tissues/samples/mutations are selected, there should be an `algorithm selector` that provides the user (presumably with little machine learning experience) a guided walkthrough of the pros and cons of each classifier. The walkthrough could include things like `interpretability` and `probability output`, etc.

**Comment by awm33** [comment]
@cgreene @gwaygenomics  A suggestion. Something me and my colleagues do is first create a PR with suggested documentation for the new API endpoints, usually under doc/api.rst or doc/api.md, before writing any code. We wrote a python script that gathers the doc markup files from each repo and renders a static HTML website. There are some API doc formats out there that may be worth checking out, like Swagger.

Our implementation is simple, but gets the job done. Maybe use this to start then switch to something swagger.

The doc section for each endpoint describes the schema for the endpoint, usually as a table, and each method supported. Along with query parameter specs, pagination, etc. Usually an example request response as well. This allows us all to agree on the API and data model, which is usually the touch points across groups or subprojects.

Here's an example. The initial commit on the PR could just be the proposed schema and maybe the methods that are needed, eventually adding examples. Permission scopes and rate limits / quota are also useful to place eventually.

Schema
=======

| Field        | Type           | Description | Read-Only
| ------------- |:-------------:| ----------:| ----------:|
| id      | integer | Entity Primary Key. Auto Incrementing. | Y |
| user_id      | integer      |   References the user who created the example. | N |
| title | string    |   Title. Max 2048 characters. | N |
| ... | ...    |   ... | ... |

Create an Example

`POST /examples`

Data

    {
        user_id: 1,
        title: "Example"
    }

Response 201

    {
        id: 1,
        user_id: 1,
        title: "Example"
    }

**Comment by awm33** [comment]
It's been decided not to have algorithms modeled at this time. This endpoint can be revisited if/when the cognoma team would like to introduce modeling algorithms.
