### ISSUE TITLE
core-service `docker-compose up` on mac < 10.12

### ISSUE THREAD

**Issue by cgreene** [cognoma/core-service#43]
Working with @aelkner here to get this working and we've been trying to get to the bottom of why `docker-compose up` works for me but not for him. We've tracked it down to this situation:
https://docs.docker.com/docker-for-mac/networking/

I will let @aelkner update this issues with the details of the workaround. @aelkner will update the readme with a note on the workaround for older macos versions.

**Comment by dcgoss** [comment]
What wasn't working for him?

**Comment by cgreene** [comment]
It was not possible for him to access `localhost:8000`. He needed to look up the IP of the container. He was able to access the `IP:8000`. I'll let him describe and update the readme with the workaround.

**Comment by dcgoss** [comment]
Just ran `docker-compose up` and was able to connect to core-service by accessing `localhost:8080`. Running Docker for Mac version 17.03.1-ce-mac5 (16048). Note that the nginx port is exposed on localhost at **_8080_** and not 8000. Closing this for now but if anyone has issues feel free to reopen or start a new issue.
