### ISSUE TITLE
api.cognoma.org not returning accurate GET responses 

### ISSUE THREAD

**Issue by bdolly** [cognoma/core-service#56]
@dhimmel @dcgoss @cgreene @awm33 
Hey guys when the front-end makes any GET requests to api.cognoma.org it is returning the same response without any data being populated. 

EXAMPLE: 
**GET**` https://api.cognoma.org/samples?disease=ACC`
**RESPONSE** 200 OK `{count: 0, next: null, previous: null, results: []}`
It should return the disease data with an array of mutations and the count should be the number of samples per disease as per the [API DOCS](https://github.com/cognoma/core-service/blob/master/doc/api.md#sample-samples), this data is used in calculations in the front-end 

This same null response is appearing for other GET requests such as 
GET `https://api.cognoma.org/samples?limit=1&disease=ACC&mutations__gene=770&mutations__gene=767&mutations__gene=4871` which is used to calculate the positive and negative for Mutations in each Disease Type

**Comment by dcgoss** [comment]
Will take a look

**Comment by dcgoss** [comment]
I can't access the AWS resources to check as I don't have a key to the account, but my first impression is that something is messed up with the database. It seems empty.

**Comment by bdolly** [comment]
My understanding of the backend (which could be entirely wrong) is that it's pretty much just the docker container hosted on AWS, is that correct? 

If so you may have to run the [load scripts](https://github.com/cognoma/core-service#loading-cancer-static-data) to pull the data in the same way you do when you run docker container locally

**Comment by dhimmel** [comment]
> I can't access the AWS resources to check as I don't have a key to the account

@cgreene let's get @dcgoss set up with the AWS.

**Comment by cgreene** [comment]
Chatted with @kurtwheeler about this who is managing the current setup. This is in process. We have been struggling a bit to get the AWS permissions just right.

**Comment by kurtwheeler** [comment]
### Draft, subject to change upon completion of the `python manage.py loaddata` command

@dhimmel and I just paired on this issue. We were able to ssh onto one of the EC2 instances via:
```
ssh -l ec2-user -i cognoma_rsa.pem 54.227.183.159
```

attach to the running docker container via
```
docker exec -i -t ecs-cognoma-core-service-5-cognoma-core-service-80c4dee8b1abf1cfda01 /bin/bash
```

and then run:

```
python manage.py acquiredata
python manage.py loaddata
```

**Comment by bdolly** [comment]
I'm getting populated responses for `/samples?disease=` however I'm not getting any for `/samples?limit=1&disease=<acronym>&mutations__gene=<entrezid>` which calculates the positive matches for the disease. 

@dhimmel @cgreene Can you give me a disease type and set of genes that you know for sure has positives so I can test with?

**Comment by kurtwheeler** [comment]
@bdolly you should take a look at #57. @dhimmel and I were able to populate all the tables except `mutations`, which is why the query involving them doesn't return anything.

**Comment by dcgoss** [comment]
Fixing #57 resolves this issue as well. Just verified that GET `https://api.cognoma.org/samples?disease=ACC` returns a fully populated response.
