### ISSUE TITLE
CORS settings need adjusted for local dev environment 

### ISSUE THREAD

**Issue by bdolly** [cognoma/core-service#72]
@dcgoss  the front-end in a local dev environment runs from `http://locahost:3000` so requests to the core-service running locally via docker at `http://localhost:8080` are not from the same origin and I think it's causing CORS issue with the `POST /classifier` request. 

Angular sends a pre-flight OPTIONS request that is throwing the error below preventing the POST request to go through 
![screen shot 2017-07-11 at 1 21 25 pm](https://user-images.githubusercontent.com/1334131/28081241-938bfbcc-663c-11e7-988d-7450b4896f3f.png)
![screen shot 2017-07-11 at 1 21 44 pm](https://user-images.githubusercontent.com/1334131/28081243-9508d6aa-663c-11e7-9a0b-d560c8d24875.png)

**Comment by dcgoss** [comment]
I remember hitting this issue maybe a week or two ago. I made some changes to my fork of cognoma/frontend that seemed to resolve the issue but haven't made a PR yet. Checking now

**Comment by dcgoss** [comment]
Perhaps not. Can you run this and tell me if you still get the issue?
```
git clone https://github.com/dcgoss/core-service.git dcgoss-core-service
cd dcgoss-core-service
docker-compose up -d --build
```

**Comment by dcgoss** [comment]
It seems like this should have been resolved by this commit: https://github.com/dcgoss/core-service/commit/6c45dd516d984fbe929f03f8f323685cfb7ec717

**Comment by bdolly** [comment]
got it working on my end, we just need to tweak some User Auth stuff at the meetup to make sure it works as expected

**Comment by dcgoss** [comment]
I actually can’t make it today because I have to host my cross country
team’s first captains’ practice. Please feel free to email me or open any
issues for me to take care of as they arise.
