### ISSUE TITLE
GET api.cognoma.org/users returns the users random_slugs array 

### ISSUE THREAD

**Issue by bdolly** [cognoma/core-service#77]
@dcgoss looks like the **GET**`/users` endpoint is returning the full user object for all users. Shouldn't this endpoint exclude the random_slugs array since we only want that returned on **POST**  `/users` and **GET** `/users/<random_slug>` ?

**Comment by dcgoss** [comment]
Yep, right on. In fact I think I’m planning to remove the /users/ list endpoint altogether unless the frontend needs it for some reason.

**Comment by bdolly** [comment]
maybe for an admin screen somewhere down the line? but should be good to remove for now
