### ISSUE TITLE
Automated Testing

### ISSUE THREAD

**Issue by cgreene** [cognoma/core-service#9]
We should set up a continuous integration framework to automatically run tests. I am at a conference and study section this week but can look into this next weekend, or if someone else wants to snag this task - feel free to assign to yourself!

**Comment by jhonjairoroa87** [comment]
@cgreene I was thinking of taking this task and link the project to https://travis-ci.org/ Any thoughts or any other preferred CI platform?

**Comment by cgreene** [comment]
@jhonjairoroa87 Wonderful! From discussions with @awm33 @dcgoss and @aelkner (mostly in https://github.com/cognoma/cognoma/issues/4 ) it sounds like we want a system that can produce a docker container after the tests. We're mostly a mercurial shop, so I have experience with codeship. I'm not too familiar with the git ecosystem. Here's what I'd say the requirements are as I know them:

* tests in docker container and can output the container.
* works with github's pull request API for testing each PR
* free for open source projects

Beyond that, the CI world is your oyster in my book :)

**Comment by Suberri** [comment]
I agree, Docker is the way to go. 
I have in depth working knowledge of CI/CD with Jenkins. 
@jhonjairoroa87 I can help you with the CI

It may be a good idea to use Pytest for unit testing.

**Comment by awm33** [comment]
@cgreene or @dhimmel can you give CircleCI access to the cognoma github org?

**Comment by awm33** [comment]
I also don't know if I'll be able to add it as an integration, I don't have access to repo settings

**Comment by dhimmel** [comment]
@awm33 are you sure you want to use CircleCI over Travis CI? [With Circle](https://circleci.com/blog/a-step-into-open-source/):

> From now on, every user and GitHub organization has three free containers to build public projects. We also now have public build pages for public projects, so your collaborators won’t have to log in to see build pages. Unauthenticated API access is now available for these projects, too, so badges no longer need purpose-specific API keys.

So if we go CircleCI we're limited to CI on three repos. I think there's a benefit to using a single CI provider for all Cognoma repos. I've found Travis to be pretty good ([example](https://travis-ci.org/dhimmel/thinklytics)).

**Comment by awm33** [comment]
> Open source projects get 3 additional free containers, so you can use the power of parallelism and/or run more than one build concurrently. 

@dhimmel containers != repo. Number of repos is unlimited.

That means we can only have a parallelism of 3, which is fine, 1 is probably ok. 

I use CircleCI at work and have a contact there. I believe @cgreene has used it as well

**Comment by dhimmel** [comment]
Okay I believe I gave CircleCI third party access to all Cognoma repos.

> That means we can only have a parallelism of 3, which is fine, 1 is probably ok.

Agreed, especially since we're not supporting a wide range of environments.

**Comment by awm33** [comment]
@dhimmel Number of containers just means how many parrallel build you can do, it's not a peristent container.

I can't add / manage it, I don't have that level of rights on `core-services` or `ml-workers`, I do on `task-service`

**Comment by dhimmel** [comment]
Okay now you should be admin on `core-service` and `ml-workers`. Let me know if I can revoke Circle CI access to entire organization -- is there a way to enable Circle CI on a repo specific level or is the current setup the best?

**Comment by awm33** [comment]
@dhimmel I think this is the intended setup. It has org access to it can list repos and I guess make sure someones not going rouge, but you have to enable it on a per repo basis. Enabling it on core-services now, will probably need to create a circle.yml file

**Comment by awm33** [comment]
https://github.com/cognoma/core-service/pull/28
